### ISSUE TITLE
Funkcija ne dela nič in zanka je neskončna

### ISSUE THREAD

**Issue by Milos016** [makieew/Vajeur10#1]
def ime(i):    #tukaj definicija ne dela kar je potrebno, ker input v drugi vrstici nič ne dela
    input('Ime: '+i)
    return ('Welcome' +i)

while a > 0: #tuki je problem što je zanka neskončna ker je a vedno več kot 0
    b += a
    a += a   # a vedno > 0
    print(b)

**Comment by makieew** [comment]
The issues are resolved.
